apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamspeak.fullname" . }}
  labels:
    {{- include "teamspeak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.voice }}
      targetPort: voice
      protocol: UDP
      name: voice
    - port: {{ .Values.service.serverQuery }}
      targetPort: serverquery
      protocol: TCP
      name: serverquery
    - port: {{ .Values.service.fileTransfer }}
      targetPort: filetransfer
      protocol: TCP
      name: filetransfer
  selector:
    {{- include "teamspeak.selectorLabels" . | nindent 4 }}
